server:
  port: ${SERVER_PORT:8080}

app:
  sso:
    cookie-name: "authToken"

spring:
  application:
    name: ${APP_NAME:api-gateway}
  
  # === Add Redis connection configuration ===
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            # For example: /api/users/me -> /api/me
            # For example: /api/users/public/register -> /api/public/register
            - RewritePath=/api/users/(?<path>.*), /api/$\{path}
            # <<< Apply Rate Limit Filter >>>
            - name: RequestRateLimiter
              args:
                # Use the bean we defined in RateLimiterConfig
                key-resolver: "#{@ipKeyResolver}"
                # Configure the Redis rate limiter
                redis-rate-limiter:
                  replenishRate: 10   # Token bucket fill rate per second: Allows 10 requests per second
                  burstCapacity: 20   # Total Token Bucket Capacity: Allows 20 instantaneous requests

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
              # For example: /api/auth/public/login -> /api/public/login
              # For example: /api/auth/logout -> /api/logout
            - RewritePath=/api/auth/(?<path>.*), /api/$\{path}
            # <<< also applies a rate-limiting >>> to the authentication service
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20

        - id: project-service-route
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - RewritePath=/api/projects/(?<path>.*), /api/projects/$\{path}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20