server:
  port: ${SERVER_PORT:9400}

spring:
  application:
    name: ${APP_NAME:notification-service}

  # === RabbitMQ Configuration ===
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: user
    password: pass

  # === RabbitMQ Declarations ===
  # Ensures the exchange, queue, and binding exist before the listener starts.
  amqp:
    declarations:
      - exchange:
          name: notification.exchange
          type: topic
          durable: true
      - queue:
          name: email.queue
          durable: true
      - binding:
          destination: email.queue
          exchange: notification.exchange
          routingKey: email.routing.key

  # === Java Mail Sender (SMTP) Configuration ===
  # !!! IMPORTANT !!!
#  mail:
#    host: smtp.example.com
#    port: 587
#    username: your-smtp-username
#    password: your-smtp-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

