spring:
  application:
    name: ${APP_NAME:api-gateway}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 300000
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}