events {}

http {
    server {
        listen 80;

        location /react/ {
            proxy_pass http://react-portal:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

#         location /flutter/ {
#             # flutter run -d chrome --web-hostname=0.0.0.0 --web-port=8082
#             proxy_pass http://host.docker.internal:8082;
#
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#             proxy_set_header Upgrade $http_upgrade;
#             proxy_set_header Connection "Upgrade";
#
#             # 1. Turn off proxy buffering and let data pass through immediately. This is at the heart of solving the problem of HMR slowness.
#             proxy_buffering off;
#
#             # 2. Increase the timeout period to prevent the WebSocket from being accidentally disconnected due to inactivity (e.g. long debugging time)
#             proxy_read_timeout 1600s;
#             proxy_send_timeout 1600s;
#         }

        location /flutter/ {
            proxy_pass http://flutter-app:8082;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_buffering off;
            proxy_read_timeout 1600s;
            proxy_send_timeout 1600s;
        }

        location /api/ {
            # Proxy to the microservice backend, port 8080 of the host
            proxy_pass http://host.docker.internal:8080;

            # Generic proxy header
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}